version: '3.1'
services:
  user-mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'users-db'
      MYSQL_ROOT_PASSWORD: 'password'
